To dolistmarkup
Johnr302/to-do pull request #2
Opened 2019-08-06 14:15 UTC by Johnr302

please check added content and formatting

2019-08-06 15:00 UTC, d48 requested changes

2019-08-06 15:00 UTC, d48 commented on .vscode/settings.json
> +}
add this file to `.gitignore`. You don't want this in your code repo if it's only your local configuration settings

2019-08-06 15:00 UTC, d48 commented on to-do.html
> +<html lang="en">
great

2019-08-06 15:00 UTC, d48 commented on to-do.html
> +    <link rel="stylesheet" href="styles.css" />
make sure this links to the correct stylesheet file

2019-08-06 15:00 UTC, d48 commented on to-do.html
> +    <title>Pjohn's to do list help!</title>
why does it say `help!`

2019-08-06 15:00 UTC, d48 commented on to-do.html
> +        <li><input type="text" id="l1" /></li>
tell me more about this ending `/`

2019-08-06 15:00 UTC, d48 commented on to-do.html
> +    <footer>information here</footer>
update this with the actual information

2019-08-06 19:30 UTC, Johnr302 commented on to-do.html
> +        <li><input type="text" id="l1" /></li>
it closes the input tag inside the li tag. the code formatter puts them in there. web examples do not show the /

2019-08-06 19:30 UTC, Johnr302 commented on to-do.html
> +        <li><input type="text" id="l1" /></li>
rules in XML required all tags to be opened and closed

2019-08-06 21:16 UTC, d48 commented on to-do.css
> +  /*background-image: url(images/bg_page.png);*/
didn't notice this commented out code. Remove if you're not going to use it

2019-08-06 21:17 UTC, d48 commented
I just have final 2 comments. If you update those I'll merge this pull request 👍

2019-08-07 14:26 UTC, d48 approved these changes
all looks bueno 👍

2019-08-07 14:27 UTC, merged